# sra: ["ERR315327","ERR315394"]
sra: ["SRR791578", "SRR791579", "SRR791580", "SRR791581", "SRR791582", "SRR791583", "SRR791584", "SRR791585", "SRR791586"] # jurkat
# sra: ["SRR2153519", "SRR2153520"] # mcf7
