### Using SRAs
sra: ["SRX791580"]
# sra: ["SRR791578", "SRR791579", "SRR791580", "SRR791581", "SRR791582", "SRR791583", "SRR791584", "SRR791585", "SRR791586"]
# sra: ["SRR2153519", "SRR2153520"] # mcf7

### Using FASTQs
# sra: [] #  can leave empty sras as 1) empty list 2) undefined/null
# fq1: ["exp1", "exp2"]
# fq2: ["exp1", "exp2"]

### Define own directory
analysisDirectory: "AnalysisFolder"
