channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.6
  - star =2.6.0c
  - gatk4 =4.0.11.0
  - hisat2 =2.1.0
  - samtools =1.9
  - sra-tools
  - stringtie
  - biopython
  #- vcftools =0.1.15
